### ISSUE TITLE
APK download?

### ISSUE THREAD

**Issue by IzzySoft** [nemuTUI/nemu-droid#2]
Would you consider making the APK of your app available to those outside of Google's walled garden (without PlayStore access) – e.g. by [tagging releases](https://github.com/nemuTUI/nemu-droid/releases) and attaching the APK there? Thanks in advance!

**Comment by 0x501D** [comment]
No problem, I'll do it.

**Comment by IzzySoft** [comment]
Thanks a lot! Your app will then become [available here](https://apt.izzysoft.de/fdroid/index/apk/nemutui.com.github.nemu_droid) with the next sync around 7 pm UTC today (updates will be checked for and retrieved within 24h of your making a new release and attaching the APK to it – users then will be notified via their F-Droid clients). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany Google's in your Readme and link there :smiley:
